language: java

jobs:
  include:
    - stage: CodeQuality
      script: ./gradlew sonarqube
    - stage: Docker
      if: branch = master
      script: ./gradlew dockerPush
      before_script:
        - echo "$DOCKER_PASSWORT" | docker login -u "$DOCKER_USERNAME" --pasword-stdin

addons:
  sonarcloud:
    organization: $SONAR_USER
    token:
      secure: $SONAR_TOKEN
     
jdk:
  - openjdk11
